<?php

namespace App\Models;

use App\Notifications\CommentPlanNotification;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Notification;

class Comment extends Model
{
    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function plan()
    {
        return $this->belongsTo(Plan::class);
    }

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        self::created(function ($model){

            $plan = $model->plan;
            $users = $plan->account->users()->where('account_user.notify', '1')->get();
            Notification::send($users, new CommentPlanNotification($plan));

        });
    }
}
