<?php

namespace App\Models;

use App\Notifications\CommentPlanNotification;
use App\Notifications\CreatePlanNotification;
use App\Notifications\StatusPlanNotification;
use App\Notifications\UpdatedPlanNotification;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Notification;

class Plan extends Model
{
    protected $dates = ['public_at'];

    public function comment()
    {
        return $this->hasMany(Comment::class);
    }

    public function comment_no_apply()
    {
        return $this->hasMany(Comment::class)->where('apply','!=','1')->count();
    }
    public function comment_apply()
    {
        return $this->hasMany(Comment::class)->where('apply','1')->count();
    }

    public function account()
    {
        return $this->belongsTo(Account::class);
    }

    public function images()
    {
        return $this->hasMany(Image::class)->orderBy('order_image');
    }

    public function videos()
    {
        return $this->hasMany(Video::class)->orderBy('order_video');
    }

    public function youtubes()
    {
        return $this->hasMany(Youtube::class);
    }

    public function status()
    {
        return $this->belongsTo(Status::class);
    }

    public function tags()
    {
        return $this->belongsToMany(Tag::class);
    }

    public function socnets()
    {
        return $this->belongsToMany(Socnet::class);
    }

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        self::created(function ($plan) {
            $users = $plan->account->users()->where('account_user.notify', '1')->get();
            Notification::send($users, new CreatePlanNotification($plan));
        });

        self::updated(function ($plan) {
            $users = $plan->account->users()->where('account_user.notify', '1')->get();
            if ($plan->isDirty('status_id')) {
                $dirty = $plan->getDirty();
                if ($dirty['status_id'] == 3) {
                    Notification::send($users, new StatusPlanNotification($plan));
                }
            }
            if ($plan->isDirty('comment')) {
                //Notification::send($users, new CommentPlanNotification($plan));
            } else {
                //Notification::send($users, new UpdatedPlanNotification($plan));
            }


        });

    }
}
